spring:
  application:
    name: emergencyWardPanels

application:
  backend:
    host: localhost
    port: 9091
    run-over-https: false
  keycloak:
    url: https://localhost:8443/
    realm: test-realm
    client-id: panels-microservice
    client-secret: z58ctuc2aknkZovjZb0j0bO570lDiAda
    schedule:
      refresh-rate: 30000
