spring:
  application:
    name: emergencyWardPanels

application:
  keycloak:
    url: https://localhost:8443/
    realm: test-realm
    client-id: panels-microservice
    client-secret: z58ctuc2aknkZovjZb0j0bO570lDiAda
    schedule:
      refresh-rate: 30000
