spring:
  application:
    name: emergencyWardPanels

application:
  core:
    task:
      #In milliseconds
      send-data-rate: 5000
  backend:
    host: ${BACKEND_HOST}
    port: ${BACKEND_PORT}
    run-over-https: ${BACKEND_HTTPS}
  keycloak:
    url: ${KC_URL}
    realm: ${KC_REALM}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    schedule:
      #In milliseconds
      refresh-rate: 30000

#WebSocket Configuration and protection
server:
  port: ${WS_PORT}
  ssl:
    enabled: ${WS_HTTPS}
    certificate-private-key: ${WS_HTTPS_PRIVATE_KEY}
    certificate: ${WS_HTTPS_CERTIFICATE}
    trust-certificate: ${WS_HTTPS_TRUSTED_CERTIFICATE_COLLECTION}
