// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: appointment.proto
// Protobuf Java Version: 4.29.1

package com.git_commit_therapy.proto;

public final class AppointmentOuterClass {
  private AppointmentOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      AppointmentOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppointmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.git_commit_therapy.proto.Appointment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 appointmentId = 1;</code>
     * @return The appointmentId.
     */
    int getAppointmentId();

    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return Whether the dateTime field is set.
     */
    boolean hasDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return The dateTime.
     */
    com.google.protobuf.Timestamp getDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
     * @return Whether the staff field is set.
     */
    boolean hasStaff();
    /**
     * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
     * @return The staff.
     */
    UserOuterClass.Staff getStaff();
    /**
     * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
     */
    UserOuterClass.StaffOrBuilder getStaffOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
     * @return Whether the doctor field is set.
     */
    boolean hasDoctor();
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
     * @return The doctor.
     */
    UserOuterClass.Doctor getDoctor();
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
     */
    UserOuterClass.DoctorOrBuilder getDoctorOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
     * @return Whether the patient field is set.
     */
    boolean hasPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
     * @return The patient.
     */
    UserOuterClass.Patient getPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
     */
    UserOuterClass.PatientOrBuilder getPatientOrBuilder();
  }
  /**
   * Protobuf type {@code com.git_commit_therapy.proto.Appointment}
   */
  public static final class Appointment extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.git_commit_therapy.proto.Appointment)
      AppointmentOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Appointment.class.getName());
    }
    // Use Appointment.newBuilder() to construct.
    private Appointment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Appointment() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_git_commit_therapy_proto_Appointment_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_git_commit_therapy_proto_Appointment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.git_commit_therapy.proto.AppointmentOuterClass.Appointment.class, com.git_commit_therapy.proto.AppointmentOuterClass.Appointment.Builder.class);
    }

    private int bitField0_;
    public static final int APPOINTMENTID_FIELD_NUMBER = 1;
    private int appointmentId_ = 0;
    /**
     * <code>int32 appointmentId = 1;</code>
     * @return The appointmentId.
     */
    @Override
    public int getAppointmentId() {
      return appointmentId_;
    }

    public static final int DATETIME_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp dateTime_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return Whether the dateTime field is set.
     */
    @Override
    public boolean hasDateTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return The dateTime.
     */
    @Override
    public com.google.protobuf.Timestamp getDateTime() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }

    public static final int STAFF_FIELD_NUMBER = 3;
    private UserOuterClass.Staff staff_;
    /**
     * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
     * @return Whether the staff field is set.
     */
    @Override
    public boolean hasStaff() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
     * @return The staff.
     */
    @Override
    public UserOuterClass.Staff getStaff() {
      return staff_ == null ? UserOuterClass.Staff.getDefaultInstance() : staff_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
     */
    @Override
    public UserOuterClass.StaffOrBuilder getStaffOrBuilder() {
      return staff_ == null ? UserOuterClass.Staff.getDefaultInstance() : staff_;
    }

    public static final int DOCTOR_FIELD_NUMBER = 4;
    private UserOuterClass.Doctor doctor_;
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
     * @return Whether the doctor field is set.
     */
    @Override
    public boolean hasDoctor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
     * @return The doctor.
     */
    @Override
    public UserOuterClass.Doctor getDoctor() {
      return doctor_ == null ? UserOuterClass.Doctor.getDefaultInstance() : doctor_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
     */
    @Override
    public UserOuterClass.DoctorOrBuilder getDoctorOrBuilder() {
      return doctor_ == null ? UserOuterClass.Doctor.getDefaultInstance() : doctor_;
    }

    public static final int PATIENT_FIELD_NUMBER = 5;
    private UserOuterClass.Patient patient_;
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
     * @return Whether the patient field is set.
     */
    @Override
    public boolean hasPatient() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
     * @return The patient.
     */
    @Override
    public UserOuterClass.Patient getPatient() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
     */
    @Override
    public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (appointmentId_ != 0) {
        output.writeInt32(1, appointmentId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getDateTime());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getStaff());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(4, getDoctor());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(5, getPatient());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (appointmentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, appointmentId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDateTime());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStaff());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDoctor());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPatient());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.git_commit_therapy.proto.AppointmentOuterClass.Appointment)) {
        return super.equals(obj);
      }
      com.git_commit_therapy.proto.AppointmentOuterClass.Appointment other = (com.git_commit_therapy.proto.AppointmentOuterClass.Appointment) obj;

      if (getAppointmentId()
          != other.getAppointmentId()) return false;
      if (hasDateTime() != other.hasDateTime()) return false;
      if (hasDateTime()) {
        if (!getDateTime()
            .equals(other.getDateTime())) return false;
      }
      if (hasStaff() != other.hasStaff()) return false;
      if (hasStaff()) {
        if (!getStaff()
            .equals(other.getStaff())) return false;
      }
      if (hasDoctor() != other.hasDoctor()) return false;
      if (hasDoctor()) {
        if (!getDoctor()
            .equals(other.getDoctor())) return false;
      }
      if (hasPatient() != other.hasPatient()) return false;
      if (hasPatient()) {
        if (!getPatient()
            .equals(other.getPatient())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPOINTMENTID_FIELD_NUMBER;
      hash = (53 * hash) + getAppointmentId();
      if (hasDateTime()) {
        hash = (37 * hash) + DATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getDateTime().hashCode();
      }
      if (hasStaff()) {
        hash = (37 * hash) + STAFF_FIELD_NUMBER;
        hash = (53 * hash) + getStaff().hashCode();
      }
      if (hasDoctor()) {
        hash = (37 * hash) + DOCTOR_FIELD_NUMBER;
        hash = (53 * hash) + getDoctor().hashCode();
      }
      if (hasPatient()) {
        hash = (37 * hash) + PATIENT_FIELD_NUMBER;
        hash = (53 * hash) + getPatient().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.git_commit_therapy.proto.AppointmentOuterClass.Appointment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.git_commit_therapy.proto.Appointment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.git_commit_therapy.proto.Appointment)
        com.git_commit_therapy.proto.AppointmentOuterClass.AppointmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_git_commit_therapy_proto_Appointment_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_git_commit_therapy_proto_Appointment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.git_commit_therapy.proto.AppointmentOuterClass.Appointment.class, com.git_commit_therapy.proto.AppointmentOuterClass.Appointment.Builder.class);
      }

      // Construct using com.git_commit_therapy.proto.AppointmentOuterClass.Appointment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getDateTimeFieldBuilder();
          getStaffFieldBuilder();
          getDoctorFieldBuilder();
          getPatientFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        appointmentId_ = 0;
        dateTime_ = null;
        if (dateTimeBuilder_ != null) {
          dateTimeBuilder_.dispose();
          dateTimeBuilder_ = null;
        }
        staff_ = null;
        if (staffBuilder_ != null) {
          staffBuilder_.dispose();
          staffBuilder_ = null;
        }
        doctor_ = null;
        if (doctorBuilder_ != null) {
          doctorBuilder_.dispose();
          doctorBuilder_ = null;
        }
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_git_commit_therapy_proto_Appointment_descriptor;
      }

      @Override
      public com.git_commit_therapy.proto.AppointmentOuterClass.Appointment getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.git_commit_therapy.proto.AppointmentOuterClass.Appointment build() {
        com.git_commit_therapy.proto.AppointmentOuterClass.Appointment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.git_commit_therapy.proto.AppointmentOuterClass.Appointment buildPartial() {
        com.git_commit_therapy.proto.AppointmentOuterClass.Appointment result = new com.git_commit_therapy.proto.AppointmentOuterClass.Appointment(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.git_commit_therapy.proto.AppointmentOuterClass.Appointment result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.appointmentId_ = appointmentId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dateTime_ = dateTimeBuilder_ == null
              ? dateTime_
              : dateTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.staff_ = staffBuilder_ == null
              ? staff_
              : staffBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.doctor_ = doctorBuilder_ == null
              ? doctor_
              : doctorBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.patient_ = patientBuilder_ == null
              ? patient_
              : patientBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.git_commit_therapy.proto.AppointmentOuterClass.Appointment) {
          return mergeFrom((com.git_commit_therapy.proto.AppointmentOuterClass.Appointment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.git_commit_therapy.proto.AppointmentOuterClass.Appointment other) {
        if (other == getDefaultInstance()) return this;
        if (other.getAppointmentId() != 0) {
          setAppointmentId(other.getAppointmentId());
        }
        if (other.hasDateTime()) {
          mergeDateTime(other.getDateTime());
        }
        if (other.hasStaff()) {
          mergeStaff(other.getStaff());
        }
        if (other.hasDoctor()) {
          mergeDoctor(other.getDoctor());
        }
        if (other.hasPatient()) {
          mergePatient(other.getPatient());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                appointmentId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getDateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getStaffFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getDoctorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getPatientFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int appointmentId_ ;
      /**
       * <code>int32 appointmentId = 1;</code>
       * @return The appointmentId.
       */
      @Override
      public int getAppointmentId() {
        return appointmentId_;
      }
      /**
       * <code>int32 appointmentId = 1;</code>
       * @param value The appointmentId to set.
       * @return This builder for chaining.
       */
      public Builder setAppointmentId(int value) {

        appointmentId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 appointmentId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppointmentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appointmentId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dateTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       * @return Whether the dateTime field is set.
       */
      public boolean hasDateTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       * @return The dateTime.
       */
      public com.google.protobuf.Timestamp getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder setDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
        } else {
          dateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder setDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            dateTime_ != null &&
            dateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateTimeBuilder().mergeFrom(value);
          } else {
            dateTime_ = value;
          }
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }
        if (dateTime_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder clearDateTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dateTime_ = null;
        if (dateTimeBuilder_ != null) {
          dateTimeBuilder_.dispose();
          dateTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateTime(),
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }

      private UserOuterClass.Staff staff_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Staff, UserOuterClass.Staff.Builder, UserOuterClass.StaffOrBuilder> staffBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       * @return Whether the staff field is set.
       */
      public boolean hasStaff() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       * @return The staff.
       */
      public UserOuterClass.Staff getStaff() {
        if (staffBuilder_ == null) {
          return staff_ == null ? UserOuterClass.Staff.getDefaultInstance() : staff_;
        } else {
          return staffBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      public Builder setStaff(UserOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          staff_ = value;
        } else {
          staffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      public Builder setStaff(
          UserOuterClass.Staff.Builder builderForValue) {
        if (staffBuilder_ == null) {
          staff_ = builderForValue.build();
        } else {
          staffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      public Builder mergeStaff(UserOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            staff_ != null &&
            staff_ != UserOuterClass.Staff.getDefaultInstance()) {
            getStaffBuilder().mergeFrom(value);
          } else {
            staff_ = value;
          }
        } else {
          staffBuilder_.mergeFrom(value);
        }
        if (staff_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      public Builder clearStaff() {
        bitField0_ = (bitField0_ & ~0x00000004);
        staff_ = null;
        if (staffBuilder_ != null) {
          staffBuilder_.dispose();
          staffBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      public UserOuterClass.Staff.Builder getStaffBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getStaffFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      public UserOuterClass.StaffOrBuilder getStaffOrBuilder() {
        if (staffBuilder_ != null) {
          return staffBuilder_.getMessageOrBuilder();
        } else {
          return staff_ == null ?
              UserOuterClass.Staff.getDefaultInstance() : staff_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Staff staff = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Staff, UserOuterClass.Staff.Builder, UserOuterClass.StaffOrBuilder>
          getStaffFieldBuilder() {
        if (staffBuilder_ == null) {
          staffBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Staff, UserOuterClass.Staff.Builder, UserOuterClass.StaffOrBuilder>(
                  getStaff(),
                  getParentForChildren(),
                  isClean());
          staff_ = null;
        }
        return staffBuilder_;
      }

      private UserOuterClass.Doctor doctor_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Doctor, UserOuterClass.Doctor.Builder, UserOuterClass.DoctorOrBuilder> doctorBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       * @return Whether the doctor field is set.
       */
      public boolean hasDoctor() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       * @return The doctor.
       */
      public UserOuterClass.Doctor getDoctor() {
        if (doctorBuilder_ == null) {
          return doctor_ == null ? UserOuterClass.Doctor.getDefaultInstance() : doctor_;
        } else {
          return doctorBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      public Builder setDoctor(UserOuterClass.Doctor value) {
        if (doctorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          doctor_ = value;
        } else {
          doctorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      public Builder setDoctor(
          UserOuterClass.Doctor.Builder builderForValue) {
        if (doctorBuilder_ == null) {
          doctor_ = builderForValue.build();
        } else {
          doctorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      public Builder mergeDoctor(UserOuterClass.Doctor value) {
        if (doctorBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            doctor_ != null &&
            doctor_ != UserOuterClass.Doctor.getDefaultInstance()) {
            getDoctorBuilder().mergeFrom(value);
          } else {
            doctor_ = value;
          }
        } else {
          doctorBuilder_.mergeFrom(value);
        }
        if (doctor_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      public Builder clearDoctor() {
        bitField0_ = (bitField0_ & ~0x00000008);
        doctor_ = null;
        if (doctorBuilder_ != null) {
          doctorBuilder_.dispose();
          doctorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      public UserOuterClass.Doctor.Builder getDoctorBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDoctorFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      public UserOuterClass.DoctorOrBuilder getDoctorOrBuilder() {
        if (doctorBuilder_ != null) {
          return doctorBuilder_.getMessageOrBuilder();
        } else {
          return doctor_ == null ?
              UserOuterClass.Doctor.getDefaultInstance() : doctor_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Doctor, UserOuterClass.Doctor.Builder, UserOuterClass.DoctorOrBuilder>
          getDoctorFieldBuilder() {
        if (doctorBuilder_ == null) {
          doctorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Doctor, UserOuterClass.Doctor.Builder, UserOuterClass.DoctorOrBuilder>(
                  getDoctor(),
                  getParentForChildren(),
                  isClean());
          doctor_ = null;
        }
        return doctorBuilder_;
      }

      private UserOuterClass.Patient patient_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder> patientBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       * @return Whether the patient field is set.
       */
      public boolean hasPatient() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       * @return The patient.
       */
      public UserOuterClass.Patient getPatient() {
        if (patientBuilder_ == null) {
          return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
        } else {
          return patientBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      public Builder setPatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patient_ = value;
        } else {
          patientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      public Builder setPatient(
          UserOuterClass.Patient.Builder builderForValue) {
        if (patientBuilder_ == null) {
          patient_ = builderForValue.build();
        } else {
          patientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      public Builder mergePatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            patient_ != null &&
            patient_ != UserOuterClass.Patient.getDefaultInstance()) {
            getPatientBuilder().mergeFrom(value);
          } else {
            patient_ = value;
          }
        } else {
          patientBuilder_.mergeFrom(value);
        }
        if (patient_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      public Builder clearPatient() {
        bitField0_ = (bitField0_ & ~0x00000010);
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      public UserOuterClass.Patient.Builder getPatientBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getPatientFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
        if (patientBuilder_ != null) {
          return patientBuilder_.getMessageOrBuilder();
        } else {
          return patient_ == null ?
              UserOuterClass.Patient.getDefaultInstance() : patient_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>
          getPatientFieldBuilder() {
        if (patientBuilder_ == null) {
          patientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>(
                  getPatient(),
                  getParentForChildren(),
                  isClean());
          patient_ = null;
        }
        return patientBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.git_commit_therapy.proto.Appointment)
    }

    // @@protoc_insertion_point(class_scope:com.git_commit_therapy.proto.Appointment)
    private static final com.git_commit_therapy.proto.AppointmentOuterClass.Appointment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.git_commit_therapy.proto.AppointmentOuterClass.Appointment();
    }

    public static com.git_commit_therapy.proto.AppointmentOuterClass.Appointment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Appointment>
        PARSER = new com.google.protobuf.AbstractParser<Appointment>() {
      @Override
      public Appointment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Appointment> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Appointment> getParserForType() {
      return PARSER;
    }

    @Override
    public com.git_commit_therapy.proto.AppointmentOuterClass.Appointment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_git_commit_therapy_proto_Appointment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_git_commit_therapy_proto_Appointment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021appointment.proto\022\034com.git_commit_ther" +
      "apy.proto\032\nuser.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\364\001\n\013Appointment\022\025\n\rappoin" +
      "tmentId\030\001 \001(\005\022,\n\010dateTime\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\0222\n\005staff\030\003 \001(\0132#.com" +
      ".git_commit_therapy.proto.Staff\0224\n\006docto" +
      "r\030\004 \001(\0132$.com.git_commit_therapy.proto.D" +
      "octor\0226\n\007patient\030\005 \001(\0132%.com.git_commit_" +
      "therapy.proto.Patientb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          UserOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_git_commit_therapy_proto_Appointment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_git_commit_therapy_proto_Appointment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_git_commit_therapy_proto_Appointment_descriptor,
        new String[] { "AppointmentId", "DateTime", "Staff", "Doctor", "Patient", });
    descriptor.resolveAllFeaturesImmutable();
    UserOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
