// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: medical_exam.proto
// Protobuf Java Version: 4.29.1

package com.git_commit_therapy.proto;

public final class MedicalExamOuterClass {
  private MedicalExamOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      MedicalExamOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MedicalExamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.git_commit_therapy.proto.MedicalExam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 examId = 1;</code>
     * @return The examId.
     */
    int getExamId();

    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return Whether the dateTime field is set.
     */
    boolean hasDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return The dateTime.
     */
    com.google.protobuf.Timestamp getDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

    /**
     * <code>string medicalReport = 3;</code>
     * @return The medicalReport.
     */
    java.lang.String getMedicalReport();
    /**
     * <code>string medicalReport = 3;</code>
     * @return The bytes for medicalReport.
     */
    com.google.protobuf.ByteString
        getMedicalReportBytes();

    /**
     * <code>string examType = 4;</code>
     * @return The examType.
     */
    java.lang.String getExamType();
    /**
     * <code>string examType = 4;</code>
     * @return The bytes for examType.
     */
    com.google.protobuf.ByteString
        getExamTypeBytes();

    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
     * @return Whether the doctor field is set.
     */
    boolean hasDoctor();
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
     * @return The doctor.
     */
    UserOuterClass.Doctor getDoctor();
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
     */
    UserOuterClass.DoctorOrBuilder getDoctorOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return Whether the patient field is set.
     */
    boolean hasPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return The patient.
     */
    UserOuterClass.Patient getPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     */
    UserOuterClass.PatientOrBuilder getPatientOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
     * @return Whether the medicalEvent field is set.
     */
    boolean hasMedicalEvent();
    /**
     * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
     * @return The medicalEvent.
     */
    MedicalEventOuterClass.MedicalEvent getMedicalEvent();
    /**
     * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
     */
    MedicalEventOuterClass.MedicalEventOrBuilder getMedicalEventOrBuilder();
  }
  /**
   * Protobuf type {@code com.git_commit_therapy.proto.MedicalExam}
   */
  public static final class MedicalExam extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.git_commit_therapy.proto.MedicalExam)
      MedicalExamOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        MedicalExam.class.getName());
    }
    // Use MedicalExam.newBuilder() to construct.
    private MedicalExam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MedicalExam() {
      medicalReport_ = "";
      examType_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MedicalExamOuterClass.internal_static_com_git_commit_therapy_proto_MedicalExam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MedicalExamOuterClass.internal_static_com_git_commit_therapy_proto_MedicalExam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MedicalExamOuterClass.MedicalExam.class, MedicalExamOuterClass.MedicalExam.Builder.class);
    }

    private int bitField0_;
    public static final int EXAMID_FIELD_NUMBER = 1;
    private int examId_ = 0;
    /**
     * <code>int32 examId = 1;</code>
     * @return The examId.
     */
    @java.lang.Override
    public int getExamId() {
      return examId_;
    }

    public static final int DATETIME_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp dateTime_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return Whether the dateTime field is set.
     */
    @java.lang.Override
    public boolean hasDateTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     * @return The dateTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDateTime() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }

    public static final int MEDICALREPORT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object medicalReport_ = "";
    /**
     * <code>string medicalReport = 3;</code>
     * @return The medicalReport.
     */
    @java.lang.Override
    public java.lang.String getMedicalReport() {
      java.lang.Object ref = medicalReport_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicalReport_ = s;
        return s;
      }
    }
    /**
     * <code>string medicalReport = 3;</code>
     * @return The bytes for medicalReport.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMedicalReportBytes() {
      java.lang.Object ref = medicalReport_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicalReport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXAMTYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object examType_ = "";
    /**
     * <code>string examType = 4;</code>
     * @return The examType.
     */
    @java.lang.Override
    public java.lang.String getExamType() {
      java.lang.Object ref = examType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        examType_ = s;
        return s;
      }
    }
    /**
     * <code>string examType = 4;</code>
     * @return The bytes for examType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExamTypeBytes() {
      java.lang.Object ref = examType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        examType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCTOR_FIELD_NUMBER = 5;
    private UserOuterClass.Doctor doctor_;
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
     * @return Whether the doctor field is set.
     */
    @java.lang.Override
    public boolean hasDoctor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
     * @return The doctor.
     */
    @java.lang.Override
    public UserOuterClass.Doctor getDoctor() {
      return doctor_ == null ? UserOuterClass.Doctor.getDefaultInstance() : doctor_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
     */
    @java.lang.Override
    public UserOuterClass.DoctorOrBuilder getDoctorOrBuilder() {
      return doctor_ == null ? UserOuterClass.Doctor.getDefaultInstance() : doctor_;
    }

    public static final int PATIENT_FIELD_NUMBER = 6;
    private UserOuterClass.Patient patient_;
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return Whether the patient field is set.
     */
    @java.lang.Override
    public boolean hasPatient() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return The patient.
     */
    @java.lang.Override
    public UserOuterClass.Patient getPatient() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     */
    @java.lang.Override
    public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }

    public static final int MEDICALEVENT_FIELD_NUMBER = 7;
    private MedicalEventOuterClass.MedicalEvent medicalEvent_;
    /**
     * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
     * @return Whether the medicalEvent field is set.
     */
    @java.lang.Override
    public boolean hasMedicalEvent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
     * @return The medicalEvent.
     */
    @java.lang.Override
    public MedicalEventOuterClass.MedicalEvent getMedicalEvent() {
      return medicalEvent_ == null ? MedicalEventOuterClass.MedicalEvent.getDefaultInstance() : medicalEvent_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
     */
    @java.lang.Override
    public MedicalEventOuterClass.MedicalEventOrBuilder getMedicalEventOrBuilder() {
      return medicalEvent_ == null ? MedicalEventOuterClass.MedicalEvent.getDefaultInstance() : medicalEvent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (examId_ != 0) {
        output.writeInt32(1, examId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getDateTime());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(medicalReport_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, medicalReport_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(examType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, examType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(5, getDoctor());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(6, getPatient());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(7, getMedicalEvent());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (examId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, examId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDateTime());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(medicalReport_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, medicalReport_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(examType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, examType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDoctor());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getPatient());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getMedicalEvent());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MedicalExamOuterClass.MedicalExam)) {
        return super.equals(obj);
      }
      MedicalExamOuterClass.MedicalExam other = (MedicalExamOuterClass.MedicalExam) obj;

      if (getExamId()
          != other.getExamId()) return false;
      if (hasDateTime() != other.hasDateTime()) return false;
      if (hasDateTime()) {
        if (!getDateTime()
            .equals(other.getDateTime())) return false;
      }
      if (!getMedicalReport()
          .equals(other.getMedicalReport())) return false;
      if (!getExamType()
          .equals(other.getExamType())) return false;
      if (hasDoctor() != other.hasDoctor()) return false;
      if (hasDoctor()) {
        if (!getDoctor()
            .equals(other.getDoctor())) return false;
      }
      if (hasPatient() != other.hasPatient()) return false;
      if (hasPatient()) {
        if (!getPatient()
            .equals(other.getPatient())) return false;
      }
      if (hasMedicalEvent() != other.hasMedicalEvent()) return false;
      if (hasMedicalEvent()) {
        if (!getMedicalEvent()
            .equals(other.getMedicalEvent())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXAMID_FIELD_NUMBER;
      hash = (53 * hash) + getExamId();
      if (hasDateTime()) {
        hash = (37 * hash) + DATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getDateTime().hashCode();
      }
      hash = (37 * hash) + MEDICALREPORT_FIELD_NUMBER;
      hash = (53 * hash) + getMedicalReport().hashCode();
      hash = (37 * hash) + EXAMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getExamType().hashCode();
      if (hasDoctor()) {
        hash = (37 * hash) + DOCTOR_FIELD_NUMBER;
        hash = (53 * hash) + getDoctor().hashCode();
      }
      if (hasPatient()) {
        hash = (37 * hash) + PATIENT_FIELD_NUMBER;
        hash = (53 * hash) + getPatient().hashCode();
      }
      if (hasMedicalEvent()) {
        hash = (37 * hash) + MEDICALEVENT_FIELD_NUMBER;
        hash = (53 * hash) + getMedicalEvent().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MedicalExamOuterClass.MedicalExam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MedicalExamOuterClass.MedicalExam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MedicalExamOuterClass.MedicalExam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MedicalExamOuterClass.MedicalExam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MedicalExamOuterClass.MedicalExam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.git_commit_therapy.proto.MedicalExam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.git_commit_therapy.proto.MedicalExam)
        MedicalExamOuterClass.MedicalExamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MedicalExamOuterClass.internal_static_com_git_commit_therapy_proto_MedicalExam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MedicalExamOuterClass.internal_static_com_git_commit_therapy_proto_MedicalExam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MedicalExamOuterClass.MedicalExam.class, MedicalExamOuterClass.MedicalExam.Builder.class);
      }

      // Construct using com.git_commit_therapy.proto.MedicalExamOuterClass.MedicalExam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getDateTimeFieldBuilder();
          getDoctorFieldBuilder();
          getPatientFieldBuilder();
          getMedicalEventFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        examId_ = 0;
        dateTime_ = null;
        if (dateTimeBuilder_ != null) {
          dateTimeBuilder_.dispose();
          dateTimeBuilder_ = null;
        }
        medicalReport_ = "";
        examType_ = "";
        doctor_ = null;
        if (doctorBuilder_ != null) {
          doctorBuilder_.dispose();
          doctorBuilder_ = null;
        }
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        medicalEvent_ = null;
        if (medicalEventBuilder_ != null) {
          medicalEventBuilder_.dispose();
          medicalEventBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MedicalExamOuterClass.internal_static_com_git_commit_therapy_proto_MedicalExam_descriptor;
      }

      @java.lang.Override
      public MedicalExamOuterClass.MedicalExam getDefaultInstanceForType() {
        return MedicalExamOuterClass.MedicalExam.getDefaultInstance();
      }

      @java.lang.Override
      public MedicalExamOuterClass.MedicalExam build() {
        MedicalExamOuterClass.MedicalExam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MedicalExamOuterClass.MedicalExam buildPartial() {
        MedicalExamOuterClass.MedicalExam result = new MedicalExamOuterClass.MedicalExam(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MedicalExamOuterClass.MedicalExam result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.examId_ = examId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dateTime_ = dateTimeBuilder_ == null
              ? dateTime_
              : dateTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.medicalReport_ = medicalReport_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.examType_ = examType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.doctor_ = doctorBuilder_ == null
              ? doctor_
              : doctorBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.patient_ = patientBuilder_ == null
              ? patient_
              : patientBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.medicalEvent_ = medicalEventBuilder_ == null
              ? medicalEvent_
              : medicalEventBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MedicalExamOuterClass.MedicalExam) {
          return mergeFrom((MedicalExamOuterClass.MedicalExam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MedicalExamOuterClass.MedicalExam other) {
        if (other == MedicalExamOuterClass.MedicalExam.getDefaultInstance()) return this;
        if (other.getExamId() != 0) {
          setExamId(other.getExamId());
        }
        if (other.hasDateTime()) {
          mergeDateTime(other.getDateTime());
        }
        if (!other.getMedicalReport().isEmpty()) {
          medicalReport_ = other.medicalReport_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getExamType().isEmpty()) {
          examType_ = other.examType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasDoctor()) {
          mergeDoctor(other.getDoctor());
        }
        if (other.hasPatient()) {
          mergePatient(other.getPatient());
        }
        if (other.hasMedicalEvent()) {
          mergeMedicalEvent(other.getMedicalEvent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                examId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getDateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                medicalReport_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                examType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getDoctorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getPatientFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getMedicalEventFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int examId_ ;
      /**
       * <code>int32 examId = 1;</code>
       * @return The examId.
       */
      @java.lang.Override
      public int getExamId() {
        return examId_;
      }
      /**
       * <code>int32 examId = 1;</code>
       * @param value The examId to set.
       * @return This builder for chaining.
       */
      public Builder setExamId(int value) {

        examId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 examId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExamId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        examId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dateTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       * @return Whether the dateTime field is set.
       */
      public boolean hasDateTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       * @return The dateTime.
       */
      public com.google.protobuf.Timestamp getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder setDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
        } else {
          dateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder setDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            dateTime_ != null &&
            dateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateTimeBuilder().mergeFrom(value);
          } else {
            dateTime_ = value;
          }
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }
        if (dateTime_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder clearDateTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dateTime_ = null;
        if (dateTimeBuilder_ != null) {
          dateTimeBuilder_.dispose();
          dateTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateTime(),
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }

      private java.lang.Object medicalReport_ = "";
      /**
       * <code>string medicalReport = 3;</code>
       * @return The medicalReport.
       */
      public java.lang.String getMedicalReport() {
        java.lang.Object ref = medicalReport_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          medicalReport_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string medicalReport = 3;</code>
       * @return The bytes for medicalReport.
       */
      public com.google.protobuf.ByteString
          getMedicalReportBytes() {
        java.lang.Object ref = medicalReport_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medicalReport_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string medicalReport = 3;</code>
       * @param value The medicalReport to set.
       * @return This builder for chaining.
       */
      public Builder setMedicalReport(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        medicalReport_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string medicalReport = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMedicalReport() {
        medicalReport_ = getDefaultInstance().getMedicalReport();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string medicalReport = 3;</code>
       * @param value The bytes for medicalReport to set.
       * @return This builder for chaining.
       */
      public Builder setMedicalReportBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        medicalReport_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object examType_ = "";
      /**
       * <code>string examType = 4;</code>
       * @return The examType.
       */
      public java.lang.String getExamType() {
        java.lang.Object ref = examType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          examType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string examType = 4;</code>
       * @return The bytes for examType.
       */
      public com.google.protobuf.ByteString
          getExamTypeBytes() {
        java.lang.Object ref = examType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          examType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string examType = 4;</code>
       * @param value The examType to set.
       * @return This builder for chaining.
       */
      public Builder setExamType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        examType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string examType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExamType() {
        examType_ = getDefaultInstance().getExamType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string examType = 4;</code>
       * @param value The bytes for examType to set.
       * @return This builder for chaining.
       */
      public Builder setExamTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        examType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private UserOuterClass.Doctor doctor_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Doctor, UserOuterClass.Doctor.Builder, UserOuterClass.DoctorOrBuilder> doctorBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       * @return Whether the doctor field is set.
       */
      public boolean hasDoctor() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       * @return The doctor.
       */
      public UserOuterClass.Doctor getDoctor() {
        if (doctorBuilder_ == null) {
          return doctor_ == null ? UserOuterClass.Doctor.getDefaultInstance() : doctor_;
        } else {
          return doctorBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      public Builder setDoctor(UserOuterClass.Doctor value) {
        if (doctorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          doctor_ = value;
        } else {
          doctorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      public Builder setDoctor(
          UserOuterClass.Doctor.Builder builderForValue) {
        if (doctorBuilder_ == null) {
          doctor_ = builderForValue.build();
        } else {
          doctorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      public Builder mergeDoctor(UserOuterClass.Doctor value) {
        if (doctorBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            doctor_ != null &&
            doctor_ != UserOuterClass.Doctor.getDefaultInstance()) {
            getDoctorBuilder().mergeFrom(value);
          } else {
            doctor_ = value;
          }
        } else {
          doctorBuilder_.mergeFrom(value);
        }
        if (doctor_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      public Builder clearDoctor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        doctor_ = null;
        if (doctorBuilder_ != null) {
          doctorBuilder_.dispose();
          doctorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      public UserOuterClass.Doctor.Builder getDoctorBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDoctorFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      public UserOuterClass.DoctorOrBuilder getDoctorOrBuilder() {
        if (doctorBuilder_ != null) {
          return doctorBuilder_.getMessageOrBuilder();
        } else {
          return doctor_ == null ?
              UserOuterClass.Doctor.getDefaultInstance() : doctor_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Doctor doctor = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Doctor, UserOuterClass.Doctor.Builder, UserOuterClass.DoctorOrBuilder>
          getDoctorFieldBuilder() {
        if (doctorBuilder_ == null) {
          doctorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Doctor, UserOuterClass.Doctor.Builder, UserOuterClass.DoctorOrBuilder>(
                  getDoctor(),
                  getParentForChildren(),
                  isClean());
          doctor_ = null;
        }
        return doctorBuilder_;
      }

      private UserOuterClass.Patient patient_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder> patientBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       * @return Whether the patient field is set.
       */
      public boolean hasPatient() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       * @return The patient.
       */
      public UserOuterClass.Patient getPatient() {
        if (patientBuilder_ == null) {
          return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
        } else {
          return patientBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder setPatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patient_ = value;
        } else {
          patientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder setPatient(
          UserOuterClass.Patient.Builder builderForValue) {
        if (patientBuilder_ == null) {
          patient_ = builderForValue.build();
        } else {
          patientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder mergePatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            patient_ != null &&
            patient_ != UserOuterClass.Patient.getDefaultInstance()) {
            getPatientBuilder().mergeFrom(value);
          } else {
            patient_ = value;
          }
        } else {
          patientBuilder_.mergeFrom(value);
        }
        if (patient_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder clearPatient() {
        bitField0_ = (bitField0_ & ~0x00000020);
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public UserOuterClass.Patient.Builder getPatientBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getPatientFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
        if (patientBuilder_ != null) {
          return patientBuilder_.getMessageOrBuilder();
        } else {
          return patient_ == null ?
              UserOuterClass.Patient.getDefaultInstance() : patient_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>
          getPatientFieldBuilder() {
        if (patientBuilder_ == null) {
          patientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>(
                  getPatient(),
                  getParentForChildren(),
                  isClean());
          patient_ = null;
        }
        return patientBuilder_;
      }

      private MedicalEventOuterClass.MedicalEvent medicalEvent_;
      private com.google.protobuf.SingleFieldBuilder<
          MedicalEventOuterClass.MedicalEvent, MedicalEventOuterClass.MedicalEvent.Builder, MedicalEventOuterClass.MedicalEventOrBuilder> medicalEventBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       * @return Whether the medicalEvent field is set.
       */
      public boolean hasMedicalEvent() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       * @return The medicalEvent.
       */
      public MedicalEventOuterClass.MedicalEvent getMedicalEvent() {
        if (medicalEventBuilder_ == null) {
          return medicalEvent_ == null ? MedicalEventOuterClass.MedicalEvent.getDefaultInstance() : medicalEvent_;
        } else {
          return medicalEventBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      public Builder setMedicalEvent(MedicalEventOuterClass.MedicalEvent value) {
        if (medicalEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          medicalEvent_ = value;
        } else {
          medicalEventBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      public Builder setMedicalEvent(
          MedicalEventOuterClass.MedicalEvent.Builder builderForValue) {
        if (medicalEventBuilder_ == null) {
          medicalEvent_ = builderForValue.build();
        } else {
          medicalEventBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      public Builder mergeMedicalEvent(MedicalEventOuterClass.MedicalEvent value) {
        if (medicalEventBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            medicalEvent_ != null &&
            medicalEvent_ != MedicalEventOuterClass.MedicalEvent.getDefaultInstance()) {
            getMedicalEventBuilder().mergeFrom(value);
          } else {
            medicalEvent_ = value;
          }
        } else {
          medicalEventBuilder_.mergeFrom(value);
        }
        if (medicalEvent_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      public Builder clearMedicalEvent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        medicalEvent_ = null;
        if (medicalEventBuilder_ != null) {
          medicalEventBuilder_.dispose();
          medicalEventBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      public MedicalEventOuterClass.MedicalEvent.Builder getMedicalEventBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getMedicalEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      public MedicalEventOuterClass.MedicalEventOrBuilder getMedicalEventOrBuilder() {
        if (medicalEventBuilder_ != null) {
          return medicalEventBuilder_.getMessageOrBuilder();
        } else {
          return medicalEvent_ == null ?
              MedicalEventOuterClass.MedicalEvent.getDefaultInstance() : medicalEvent_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.MedicalEvent medicalEvent = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          MedicalEventOuterClass.MedicalEvent, MedicalEventOuterClass.MedicalEvent.Builder, MedicalEventOuterClass.MedicalEventOrBuilder>
          getMedicalEventFieldBuilder() {
        if (medicalEventBuilder_ == null) {
          medicalEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              MedicalEventOuterClass.MedicalEvent, MedicalEventOuterClass.MedicalEvent.Builder, MedicalEventOuterClass.MedicalEventOrBuilder>(
                  getMedicalEvent(),
                  getParentForChildren(),
                  isClean());
          medicalEvent_ = null;
        }
        return medicalEventBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.git_commit_therapy.proto.MedicalExam)
    }

    // @@protoc_insertion_point(class_scope:com.git_commit_therapy.proto.MedicalExam)
    private static final MedicalExamOuterClass.MedicalExam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MedicalExamOuterClass.MedicalExam();
    }

    public static MedicalExamOuterClass.MedicalExam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MedicalExam>
        PARSER = new com.google.protobuf.AbstractParser<MedicalExam>() {
      @java.lang.Override
      public MedicalExam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MedicalExam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MedicalExam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MedicalExamOuterClass.MedicalExam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_git_commit_therapy_proto_MedicalExam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_git_commit_therapy_proto_MedicalExam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022medical_exam.proto\022\034com.git_commit_the" +
      "rapy.proto\032\037google/protobuf/timestamp.pr" +
      "oto\032\023medical_event.proto\032\nuser.proto\"\244\002\n" +
      "\013MedicalExam\022\016\n\006examId\030\001 \001(\005\022,\n\010dateTime" +
      "\030\002 \001(\0132\032.google.protobuf.Timestamp\022\025\n\rme" +
      "dicalReport\030\003 \001(\t\022\020\n\010examType\030\004 \001(\t\0224\n\006d" +
      "octor\030\005 \001(\0132$.com.git_commit_therapy.pro" +
      "to.Doctor\0226\n\007patient\030\006 \001(\0132%.com.git_com" +
      "mit_therapy.proto.Patient\022@\n\014medicalEven" +
      "t\030\007 \001(\0132*.com.git_commit_therapy.proto.M" +
      "edicalEventb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          MedicalEventOuterClass.getDescriptor(),
          UserOuterClass.getDescriptor(),
        });
    internal_static_com_git_commit_therapy_proto_MedicalExam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_git_commit_therapy_proto_MedicalExam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_git_commit_therapy_proto_MedicalExam_descriptor,
        new java.lang.String[] { "ExamId", "DateTime", "MedicalReport", "ExamType", "Doctor", "Patient", "MedicalEvent", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    MedicalEventOuterClass.getDescriptor();
    UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
