// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: medical_info.proto
// Protobuf Java Version: 4.29.1

package com.git_commit_therapy.proto;

public final class MedicalInfoOuterClass {
  private MedicalInfoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      MedicalInfoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MedicalInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.git_commit_therapy.proto.MedicalInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 medicalInfoId = 1;</code>
     * @return The medicalInfoId.
     */
    int getMedicalInfoId();

    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
     * @return Whether the patient field is set.
     */
    boolean hasPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
     * @return The patient.
     */
    UserOuterClass.Patient getPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
     */
    UserOuterClass.PatientOrBuilder getPatientOrBuilder();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code com.git_commit_therapy.proto.MedicalInfo}
   */
  public static final class MedicalInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.git_commit_therapy.proto.MedicalInfo)
      MedicalInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        MedicalInfo.class.getName());
    }
    // Use MedicalInfo.newBuilder() to construct.
    private MedicalInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MedicalInfo() {
      description_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MedicalInfoOuterClass.internal_static_com_git_commit_therapy_proto_MedicalInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MedicalInfoOuterClass.internal_static_com_git_commit_therapy_proto_MedicalInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MedicalInfoOuterClass.MedicalInfo.class, MedicalInfoOuterClass.MedicalInfo.Builder.class);
    }

    private int bitField0_;
    public static final int MEDICALINFOID_FIELD_NUMBER = 1;
    private int medicalInfoId_ = 0;
    /**
     * <code>int32 medicalInfoId = 1;</code>
     * @return The medicalInfoId.
     */
    @java.lang.Override
    public int getMedicalInfoId() {
      return medicalInfoId_;
    }

    public static final int PATIENT_FIELD_NUMBER = 2;
    private UserOuterClass.Patient patient_;
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
     * @return Whether the patient field is set.
     */
    @java.lang.Override
    public boolean hasPatient() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
     * @return The patient.
     */
    @java.lang.Override
    public UserOuterClass.Patient getPatient() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
     */
    @java.lang.Override
    public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (medicalInfoId_ != 0) {
        output.writeInt32(1, medicalInfoId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getPatient());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (medicalInfoId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, medicalInfoId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPatient());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MedicalInfoOuterClass.MedicalInfo)) {
        return super.equals(obj);
      }
      MedicalInfoOuterClass.MedicalInfo other = (MedicalInfoOuterClass.MedicalInfo) obj;

      if (getMedicalInfoId()
          != other.getMedicalInfoId()) return false;
      if (hasPatient() != other.hasPatient()) return false;
      if (hasPatient()) {
        if (!getPatient()
            .equals(other.getPatient())) return false;
      }
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDICALINFOID_FIELD_NUMBER;
      hash = (53 * hash) + getMedicalInfoId();
      if (hasPatient()) {
        hash = (37 * hash) + PATIENT_FIELD_NUMBER;
        hash = (53 * hash) + getPatient().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MedicalInfoOuterClass.MedicalInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MedicalInfoOuterClass.MedicalInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MedicalInfoOuterClass.MedicalInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MedicalInfoOuterClass.MedicalInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.git_commit_therapy.proto.MedicalInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.git_commit_therapy.proto.MedicalInfo)
        MedicalInfoOuterClass.MedicalInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MedicalInfoOuterClass.internal_static_com_git_commit_therapy_proto_MedicalInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MedicalInfoOuterClass.internal_static_com_git_commit_therapy_proto_MedicalInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MedicalInfoOuterClass.MedicalInfo.class, MedicalInfoOuterClass.MedicalInfo.Builder.class);
      }

      // Construct using com.git_commit_therapy.proto.MedicalInfoOuterClass.MedicalInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getPatientFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        medicalInfoId_ = 0;
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        description_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MedicalInfoOuterClass.internal_static_com_git_commit_therapy_proto_MedicalInfo_descriptor;
      }

      @java.lang.Override
      public MedicalInfoOuterClass.MedicalInfo getDefaultInstanceForType() {
        return MedicalInfoOuterClass.MedicalInfo.getDefaultInstance();
      }

      @java.lang.Override
      public MedicalInfoOuterClass.MedicalInfo build() {
        MedicalInfoOuterClass.MedicalInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MedicalInfoOuterClass.MedicalInfo buildPartial() {
        MedicalInfoOuterClass.MedicalInfo result = new MedicalInfoOuterClass.MedicalInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MedicalInfoOuterClass.MedicalInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.medicalInfoId_ = medicalInfoId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.patient_ = patientBuilder_ == null
              ? patient_
              : patientBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MedicalInfoOuterClass.MedicalInfo) {
          return mergeFrom((MedicalInfoOuterClass.MedicalInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MedicalInfoOuterClass.MedicalInfo other) {
        if (other == MedicalInfoOuterClass.MedicalInfo.getDefaultInstance()) return this;
        if (other.getMedicalInfoId() != 0) {
          setMedicalInfoId(other.getMedicalInfoId());
        }
        if (other.hasPatient()) {
          mergePatient(other.getPatient());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                medicalInfoId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getPatientFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int medicalInfoId_ ;
      /**
       * <code>int32 medicalInfoId = 1;</code>
       * @return The medicalInfoId.
       */
      @java.lang.Override
      public int getMedicalInfoId() {
        return medicalInfoId_;
      }
      /**
       * <code>int32 medicalInfoId = 1;</code>
       * @param value The medicalInfoId to set.
       * @return This builder for chaining.
       */
      public Builder setMedicalInfoId(int value) {

        medicalInfoId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 medicalInfoId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMedicalInfoId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        medicalInfoId_ = 0;
        onChanged();
        return this;
      }

      private UserOuterClass.Patient patient_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder> patientBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       * @return Whether the patient field is set.
       */
      public boolean hasPatient() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       * @return The patient.
       */
      public UserOuterClass.Patient getPatient() {
        if (patientBuilder_ == null) {
          return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
        } else {
          return patientBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      public Builder setPatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patient_ = value;
        } else {
          patientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      public Builder setPatient(
          UserOuterClass.Patient.Builder builderForValue) {
        if (patientBuilder_ == null) {
          patient_ = builderForValue.build();
        } else {
          patientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      public Builder mergePatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            patient_ != null &&
            patient_ != UserOuterClass.Patient.getDefaultInstance()) {
            getPatientBuilder().mergeFrom(value);
          } else {
            patient_ = value;
          }
        } else {
          patientBuilder_.mergeFrom(value);
        }
        if (patient_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      public Builder clearPatient() {
        bitField0_ = (bitField0_ & ~0x00000002);
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      public UserOuterClass.Patient.Builder getPatientBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPatientFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
        if (patientBuilder_ != null) {
          return patientBuilder_.getMessageOrBuilder();
        } else {
          return patient_ == null ?
              UserOuterClass.Patient.getDefaultInstance() : patient_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>
          getPatientFieldBuilder() {
        if (patientBuilder_ == null) {
          patientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>(
                  getPatient(),
                  getParentForChildren(),
                  isClean());
          patient_ = null;
        }
        return patientBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.git_commit_therapy.proto.MedicalInfo)
    }

    // @@protoc_insertion_point(class_scope:com.git_commit_therapy.proto.MedicalInfo)
    private static final MedicalInfoOuterClass.MedicalInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MedicalInfoOuterClass.MedicalInfo();
    }

    public static MedicalInfoOuterClass.MedicalInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MedicalInfo>
        PARSER = new com.google.protobuf.AbstractParser<MedicalInfo>() {
      @java.lang.Override
      public MedicalInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MedicalInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MedicalInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MedicalInfoOuterClass.MedicalInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_git_commit_therapy_proto_MedicalInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_git_commit_therapy_proto_MedicalInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022medical_info.proto\022\034com.git_commit_the" +
      "rapy.proto\032\nuser.proto\"q\n\013MedicalInfo\022\025\n" +
      "\rmedicalInfoId\030\001 \001(\005\0226\n\007patient\030\002 \001(\0132%." +
      "com.git_commit_therapy.proto.Patient\022\023\n\013" +
      "description\030\003 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          UserOuterClass.getDescriptor(),
        });
    internal_static_com_git_commit_therapy_proto_MedicalInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_git_commit_therapy_proto_MedicalInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_git_commit_therapy_proto_MedicalInfo_descriptor,
        new java.lang.String[] { "MedicalInfoId", "Patient", "Description", });
    descriptor.resolveAllFeaturesImmutable();
    UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
