// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: medical_event.proto
// Protobuf Java Version: 4.29.1

package com.git_commit_therapy.proto;

public final class MedicalEventOuterClass {
  private MedicalEventOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      MedicalEventOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.git_commit_therapy.proto.SeverityCode}
   */
  public enum SeverityCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WHITE = 0;</code>
     */
    WHITE(0),
    /**
     * <code>GREEN = 1;</code>
     */
    GREEN(1),
    /**
     * <code>YELLOW = 2;</code>
     */
    YELLOW(2),
    /**
     * <code>ORANGE = 3;</code>
     */
    ORANGE(3),
    /**
     * <code>RED = 4;</code>
     */
    RED(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        SeverityCode.class.getName());
    }
    /**
     * <code>WHITE = 0;</code>
     */
    public static final int WHITE_VALUE = 0;
    /**
     * <code>GREEN = 1;</code>
     */
    public static final int GREEN_VALUE = 1;
    /**
     * <code>YELLOW = 2;</code>
     */
    public static final int YELLOW_VALUE = 2;
    /**
     * <code>ORANGE = 3;</code>
     */
    public static final int ORANGE_VALUE = 3;
    /**
     * <code>RED = 4;</code>
     */
    public static final int RED_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SeverityCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SeverityCode forNumber(int value) {
      switch (value) {
        case 0: return WHITE;
        case 1: return GREEN;
        case 2: return YELLOW;
        case 3: return ORANGE;
        case 4: return RED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SeverityCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SeverityCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SeverityCode>() {
            public SeverityCode findValueByNumber(int number) {
              return SeverityCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MedicalEventOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final SeverityCode[] VALUES = values();

    public static SeverityCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SeverityCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.git_commit_therapy.proto.SeverityCode)
  }

  public interface MedicalEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.git_commit_therapy.proto.MedicalEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 eventId = 1;</code>
     * @return The eventId.
     */
    int getEventId();

    /**
     * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
     * @return Whether the fromDateTime field is set.
     */
    boolean hasFromDateTime();
    /**
     * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
     * @return The fromDateTime.
     */
    com.google.protobuf.Timestamp getFromDateTime();
    /**
     * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getFromDateTimeOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
     * @return Whether the toDateTime field is set.
     */
    boolean hasToDateTime();
    /**
     * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
     * @return The toDateTime.
     */
    com.google.protobuf.Timestamp getToDateTime();
    /**
     * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getToDateTimeOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
     * @return The enum numeric value on the wire for severityCode.
     */
    int getSeverityCodeValue();
    /**
     * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
     * @return The severityCode.
     */
    MedicalEventOuterClass.SeverityCode getSeverityCode();

    /**
     * <code>string dischargeLetter = 5;</code>
     * @return The dischargeLetter.
     */
    java.lang.String getDischargeLetter();
    /**
     * <code>string dischargeLetter = 5;</code>
     * @return The bytes for dischargeLetter.
     */
    com.google.protobuf.ByteString
        getDischargeLetterBytes();

    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return Whether the patient field is set.
     */
    boolean hasPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return The patient.
     */
    UserOuterClass.Patient getPatient();
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     */
    UserOuterClass.PatientOrBuilder getPatientOrBuilder();

    /**
     * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
     * @return Whether the ward field is set.
     */
    boolean hasWard();
    /**
     * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
     * @return The ward.
     */
    WardOuterClass.Ward getWard();
    /**
     * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
     */
    WardOuterClass.WardOrBuilder getWardOrBuilder();

    /**
     * <code>repeated int32 medicalExamIds = 8;</code>
     * @return A list containing the medicalExamIds.
     */
    java.util.List<java.lang.Integer> getMedicalExamIdsList();
    /**
     * <code>repeated int32 medicalExamIds = 8;</code>
     * @return The count of medicalExamIds.
     */
    int getMedicalExamIdsCount();
    /**
     * <code>repeated int32 medicalExamIds = 8;</code>
     * @param index The index of the element to return.
     * @return The medicalExamIds at the given index.
     */
    int getMedicalExamIds(int index);
  }
  /**
   * Protobuf type {@code com.git_commit_therapy.proto.MedicalEvent}
   */
  public static final class MedicalEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.git_commit_therapy.proto.MedicalEvent)
      MedicalEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        MedicalEvent.class.getName());
    }
    // Use MedicalEvent.newBuilder() to construct.
    private MedicalEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MedicalEvent() {
      severityCode_ = 0;
      dischargeLetter_ = "";
      medicalExamIds_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MedicalEventOuterClass.internal_static_com_git_commit_therapy_proto_MedicalEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MedicalEventOuterClass.internal_static_com_git_commit_therapy_proto_MedicalEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MedicalEventOuterClass.MedicalEvent.class, MedicalEventOuterClass.MedicalEvent.Builder.class);
    }

    private int bitField0_;
    public static final int EVENTID_FIELD_NUMBER = 1;
    private int eventId_ = 0;
    /**
     * <code>int32 eventId = 1;</code>
     * @return The eventId.
     */
    @java.lang.Override
    public int getEventId() {
      return eventId_;
    }

    public static final int FROMDATETIME_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp fromDateTime_;
    /**
     * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
     * @return Whether the fromDateTime field is set.
     */
    @java.lang.Override
    public boolean hasFromDateTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
     * @return The fromDateTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getFromDateTime() {
      return fromDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fromDateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getFromDateTimeOrBuilder() {
      return fromDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fromDateTime_;
    }

    public static final int TODATETIME_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp toDateTime_;
    /**
     * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
     * @return Whether the toDateTime field is set.
     */
    @java.lang.Override
    public boolean hasToDateTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
     * @return The toDateTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getToDateTime() {
      return toDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : toDateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getToDateTimeOrBuilder() {
      return toDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : toDateTime_;
    }

    public static final int SEVERITYCODE_FIELD_NUMBER = 4;
    private int severityCode_ = 0;
    /**
     * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
     * @return The enum numeric value on the wire for severityCode.
     */
    @java.lang.Override public int getSeverityCodeValue() {
      return severityCode_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
     * @return The severityCode.
     */
    @java.lang.Override public MedicalEventOuterClass.SeverityCode getSeverityCode() {
      MedicalEventOuterClass.SeverityCode result = MedicalEventOuterClass.SeverityCode.forNumber(severityCode_);
      return result == null ? MedicalEventOuterClass.SeverityCode.UNRECOGNIZED : result;
    }

    public static final int DISCHARGELETTER_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dischargeLetter_ = "";
    /**
     * <code>string dischargeLetter = 5;</code>
     * @return The dischargeLetter.
     */
    @java.lang.Override
    public java.lang.String getDischargeLetter() {
      java.lang.Object ref = dischargeLetter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dischargeLetter_ = s;
        return s;
      }
    }
    /**
     * <code>string dischargeLetter = 5;</code>
     * @return The bytes for dischargeLetter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDischargeLetterBytes() {
      java.lang.Object ref = dischargeLetter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dischargeLetter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATIENT_FIELD_NUMBER = 6;
    private UserOuterClass.Patient patient_;
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return Whether the patient field is set.
     */
    @java.lang.Override
    public boolean hasPatient() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     * @return The patient.
     */
    @java.lang.Override
    public UserOuterClass.Patient getPatient() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
     */
    @java.lang.Override
    public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
      return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
    }

    public static final int WARD_FIELD_NUMBER = 7;
    private WardOuterClass.Ward ward_;
    /**
     * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
     * @return Whether the ward field is set.
     */
    @java.lang.Override
    public boolean hasWard() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
     * @return The ward.
     */
    @java.lang.Override
    public WardOuterClass.Ward getWard() {
      return ward_ == null ? WardOuterClass.Ward.getDefaultInstance() : ward_;
    }
    /**
     * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
     */
    @java.lang.Override
    public WardOuterClass.WardOrBuilder getWardOrBuilder() {
      return ward_ == null ? WardOuterClass.Ward.getDefaultInstance() : ward_;
    }

    public static final int MEDICALEXAMIDS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList medicalExamIds_ =
        emptyIntList();
    /**
     * <code>repeated int32 medicalExamIds = 8;</code>
     * @return A list containing the medicalExamIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getMedicalExamIdsList() {
      return medicalExamIds_;
    }
    /**
     * <code>repeated int32 medicalExamIds = 8;</code>
     * @return The count of medicalExamIds.
     */
    public int getMedicalExamIdsCount() {
      return medicalExamIds_.size();
    }
    /**
     * <code>repeated int32 medicalExamIds = 8;</code>
     * @param index The index of the element to return.
     * @return The medicalExamIds at the given index.
     */
    public int getMedicalExamIds(int index) {
      return medicalExamIds_.getInt(index);
    }
    private int medicalExamIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (eventId_ != 0) {
        output.writeInt32(1, eventId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getFromDateTime());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getToDateTime());
      }
      if (severityCode_ != MedicalEventOuterClass.SeverityCode.WHITE.getNumber()) {
        output.writeEnum(4, severityCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dischargeLetter_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, dischargeLetter_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(6, getPatient());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(7, getWard());
      }
      if (getMedicalExamIdsList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(medicalExamIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < medicalExamIds_.size(); i++) {
        output.writeInt32NoTag(medicalExamIds_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, eventId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFromDateTime());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getToDateTime());
      }
      if (severityCode_ != MedicalEventOuterClass.SeverityCode.WHITE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, severityCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dischargeLetter_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, dischargeLetter_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getPatient());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getWard());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < medicalExamIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(medicalExamIds_.getInt(i));
        }
        size += dataSize;
        if (!getMedicalExamIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        medicalExamIdsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MedicalEventOuterClass.MedicalEvent)) {
        return super.equals(obj);
      }
      MedicalEventOuterClass.MedicalEvent other = (MedicalEventOuterClass.MedicalEvent) obj;

      if (getEventId()
          != other.getEventId()) return false;
      if (hasFromDateTime() != other.hasFromDateTime()) return false;
      if (hasFromDateTime()) {
        if (!getFromDateTime()
            .equals(other.getFromDateTime())) return false;
      }
      if (hasToDateTime() != other.hasToDateTime()) return false;
      if (hasToDateTime()) {
        if (!getToDateTime()
            .equals(other.getToDateTime())) return false;
      }
      if (severityCode_ != other.severityCode_) return false;
      if (!getDischargeLetter()
          .equals(other.getDischargeLetter())) return false;
      if (hasPatient() != other.hasPatient()) return false;
      if (hasPatient()) {
        if (!getPatient()
            .equals(other.getPatient())) return false;
      }
      if (hasWard() != other.hasWard()) return false;
      if (hasWard()) {
        if (!getWard()
            .equals(other.getWard())) return false;
      }
      if (!getMedicalExamIdsList()
          .equals(other.getMedicalExamIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENTID_FIELD_NUMBER;
      hash = (53 * hash) + getEventId();
      if (hasFromDateTime()) {
        hash = (37 * hash) + FROMDATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getFromDateTime().hashCode();
      }
      if (hasToDateTime()) {
        hash = (37 * hash) + TODATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getToDateTime().hashCode();
      }
      hash = (37 * hash) + SEVERITYCODE_FIELD_NUMBER;
      hash = (53 * hash) + severityCode_;
      hash = (37 * hash) + DISCHARGELETTER_FIELD_NUMBER;
      hash = (53 * hash) + getDischargeLetter().hashCode();
      if (hasPatient()) {
        hash = (37 * hash) + PATIENT_FIELD_NUMBER;
        hash = (53 * hash) + getPatient().hashCode();
      }
      if (hasWard()) {
        hash = (37 * hash) + WARD_FIELD_NUMBER;
        hash = (53 * hash) + getWard().hashCode();
      }
      if (getMedicalExamIdsCount() > 0) {
        hash = (37 * hash) + MEDICALEXAMIDS_FIELD_NUMBER;
        hash = (53 * hash) + getMedicalExamIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MedicalEventOuterClass.MedicalEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MedicalEventOuterClass.MedicalEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MedicalEventOuterClass.MedicalEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MedicalEventOuterClass.MedicalEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.git_commit_therapy.proto.MedicalEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.git_commit_therapy.proto.MedicalEvent)
        MedicalEventOuterClass.MedicalEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MedicalEventOuterClass.internal_static_com_git_commit_therapy_proto_MedicalEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MedicalEventOuterClass.internal_static_com_git_commit_therapy_proto_MedicalEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MedicalEventOuterClass.MedicalEvent.class, MedicalEventOuterClass.MedicalEvent.Builder.class);
      }

      // Construct using com.git_commit_therapy.proto.MedicalEventOuterClass.MedicalEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getFromDateTimeFieldBuilder();
          getToDateTimeFieldBuilder();
          getPatientFieldBuilder();
          getWardFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        eventId_ = 0;
        fromDateTime_ = null;
        if (fromDateTimeBuilder_ != null) {
          fromDateTimeBuilder_.dispose();
          fromDateTimeBuilder_ = null;
        }
        toDateTime_ = null;
        if (toDateTimeBuilder_ != null) {
          toDateTimeBuilder_.dispose();
          toDateTimeBuilder_ = null;
        }
        severityCode_ = 0;
        dischargeLetter_ = "";
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        ward_ = null;
        if (wardBuilder_ != null) {
          wardBuilder_.dispose();
          wardBuilder_ = null;
        }
        medicalExamIds_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MedicalEventOuterClass.internal_static_com_git_commit_therapy_proto_MedicalEvent_descriptor;
      }

      @java.lang.Override
      public MedicalEventOuterClass.MedicalEvent getDefaultInstanceForType() {
        return MedicalEventOuterClass.MedicalEvent.getDefaultInstance();
      }

      @java.lang.Override
      public MedicalEventOuterClass.MedicalEvent build() {
        MedicalEventOuterClass.MedicalEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MedicalEventOuterClass.MedicalEvent buildPartial() {
        MedicalEventOuterClass.MedicalEvent result = new MedicalEventOuterClass.MedicalEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MedicalEventOuterClass.MedicalEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.eventId_ = eventId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fromDateTime_ = fromDateTimeBuilder_ == null
              ? fromDateTime_
              : fromDateTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.toDateTime_ = toDateTimeBuilder_ == null
              ? toDateTime_
              : toDateTimeBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.severityCode_ = severityCode_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dischargeLetter_ = dischargeLetter_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.patient_ = patientBuilder_ == null
              ? patient_
              : patientBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.ward_ = wardBuilder_ == null
              ? ward_
              : wardBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          medicalExamIds_.makeImmutable();
          result.medicalExamIds_ = medicalExamIds_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MedicalEventOuterClass.MedicalEvent) {
          return mergeFrom((MedicalEventOuterClass.MedicalEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MedicalEventOuterClass.MedicalEvent other) {
        if (other == MedicalEventOuterClass.MedicalEvent.getDefaultInstance()) return this;
        if (other.getEventId() != 0) {
          setEventId(other.getEventId());
        }
        if (other.hasFromDateTime()) {
          mergeFromDateTime(other.getFromDateTime());
        }
        if (other.hasToDateTime()) {
          mergeToDateTime(other.getToDateTime());
        }
        if (other.severityCode_ != 0) {
          setSeverityCodeValue(other.getSeverityCodeValue());
        }
        if (!other.getDischargeLetter().isEmpty()) {
          dischargeLetter_ = other.dischargeLetter_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasPatient()) {
          mergePatient(other.getPatient());
        }
        if (other.hasWard()) {
          mergeWard(other.getWard());
        }
        if (!other.medicalExamIds_.isEmpty()) {
          if (medicalExamIds_.isEmpty()) {
            medicalExamIds_ = other.medicalExamIds_;
            medicalExamIds_.makeImmutable();
            bitField0_ |= 0x00000080;
          } else {
            ensureMedicalExamIdsIsMutable();
            medicalExamIds_.addAll(other.medicalExamIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                eventId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getFromDateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getToDateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                severityCode_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                dischargeLetter_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getPatientFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getWardFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                int v = input.readInt32();
                ensureMedicalExamIdsIsMutable();
                medicalExamIds_.addInt(v);
                break;
              } // case 64
              case 66: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureMedicalExamIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  medicalExamIds_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int eventId_ ;
      /**
       * <code>int32 eventId = 1;</code>
       * @return The eventId.
       */
      @java.lang.Override
      public int getEventId() {
        return eventId_;
      }
      /**
       * <code>int32 eventId = 1;</code>
       * @param value The eventId to set.
       * @return This builder for chaining.
       */
      public Builder setEventId(int value) {

        eventId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 eventId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp fromDateTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> fromDateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       * @return Whether the fromDateTime field is set.
       */
      public boolean hasFromDateTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       * @return The fromDateTime.
       */
      public com.google.protobuf.Timestamp getFromDateTime() {
        if (fromDateTimeBuilder_ == null) {
          return fromDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fromDateTime_;
        } else {
          return fromDateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      public Builder setFromDateTime(com.google.protobuf.Timestamp value) {
        if (fromDateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromDateTime_ = value;
        } else {
          fromDateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      public Builder setFromDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (fromDateTimeBuilder_ == null) {
          fromDateTime_ = builderForValue.build();
        } else {
          fromDateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      public Builder mergeFromDateTime(com.google.protobuf.Timestamp value) {
        if (fromDateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            fromDateTime_ != null &&
            fromDateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getFromDateTimeBuilder().mergeFrom(value);
          } else {
            fromDateTime_ = value;
          }
        } else {
          fromDateTimeBuilder_.mergeFrom(value);
        }
        if (fromDateTime_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      public Builder clearFromDateTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromDateTime_ = null;
        if (fromDateTimeBuilder_ != null) {
          fromDateTimeBuilder_.dispose();
          fromDateTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getFromDateTimeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFromDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getFromDateTimeOrBuilder() {
        if (fromDateTimeBuilder_ != null) {
          return fromDateTimeBuilder_.getMessageOrBuilder();
        } else {
          return fromDateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : fromDateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp fromDateTime = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getFromDateTimeFieldBuilder() {
        if (fromDateTimeBuilder_ == null) {
          fromDateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getFromDateTime(),
                  getParentForChildren(),
                  isClean());
          fromDateTime_ = null;
        }
        return fromDateTimeBuilder_;
      }

      private com.google.protobuf.Timestamp toDateTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> toDateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       * @return Whether the toDateTime field is set.
       */
      public boolean hasToDateTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       * @return The toDateTime.
       */
      public com.google.protobuf.Timestamp getToDateTime() {
        if (toDateTimeBuilder_ == null) {
          return toDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : toDateTime_;
        } else {
          return toDateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      public Builder setToDateTime(com.google.protobuf.Timestamp value) {
        if (toDateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          toDateTime_ = value;
        } else {
          toDateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      public Builder setToDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (toDateTimeBuilder_ == null) {
          toDateTime_ = builderForValue.build();
        } else {
          toDateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      public Builder mergeToDateTime(com.google.protobuf.Timestamp value) {
        if (toDateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            toDateTime_ != null &&
            toDateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getToDateTimeBuilder().mergeFrom(value);
          } else {
            toDateTime_ = value;
          }
        } else {
          toDateTimeBuilder_.mergeFrom(value);
        }
        if (toDateTime_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      public Builder clearToDateTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        toDateTime_ = null;
        if (toDateTimeBuilder_ != null) {
          toDateTimeBuilder_.dispose();
          toDateTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getToDateTimeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getToDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getToDateTimeOrBuilder() {
        if (toDateTimeBuilder_ != null) {
          return toDateTimeBuilder_.getMessageOrBuilder();
        } else {
          return toDateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : toDateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp toDateTime = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getToDateTimeFieldBuilder() {
        if (toDateTimeBuilder_ == null) {
          toDateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getToDateTime(),
                  getParentForChildren(),
                  isClean());
          toDateTime_ = null;
        }
        return toDateTimeBuilder_;
      }

      private int severityCode_ = 0;
      /**
       * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
       * @return The enum numeric value on the wire for severityCode.
       */
      @java.lang.Override public int getSeverityCodeValue() {
        return severityCode_;
      }
      /**
       * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
       * @param value The enum numeric value on the wire for severityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSeverityCodeValue(int value) {
        severityCode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
       * @return The severityCode.
       */
      @java.lang.Override
      public MedicalEventOuterClass.SeverityCode getSeverityCode() {
        MedicalEventOuterClass.SeverityCode result = MedicalEventOuterClass.SeverityCode.forNumber(severityCode_);
        return result == null ? MedicalEventOuterClass.SeverityCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
       * @param value The severityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSeverityCode(MedicalEventOuterClass.SeverityCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        severityCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.SeverityCode severityCode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeverityCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        severityCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dischargeLetter_ = "";
      /**
       * <code>string dischargeLetter = 5;</code>
       * @return The dischargeLetter.
       */
      public java.lang.String getDischargeLetter() {
        java.lang.Object ref = dischargeLetter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dischargeLetter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dischargeLetter = 5;</code>
       * @return The bytes for dischargeLetter.
       */
      public com.google.protobuf.ByteString
          getDischargeLetterBytes() {
        java.lang.Object ref = dischargeLetter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dischargeLetter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dischargeLetter = 5;</code>
       * @param value The dischargeLetter to set.
       * @return This builder for chaining.
       */
      public Builder setDischargeLetter(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dischargeLetter_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string dischargeLetter = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDischargeLetter() {
        dischargeLetter_ = getDefaultInstance().getDischargeLetter();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string dischargeLetter = 5;</code>
       * @param value The bytes for dischargeLetter to set.
       * @return This builder for chaining.
       */
      public Builder setDischargeLetterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dischargeLetter_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private UserOuterClass.Patient patient_;
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder> patientBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       * @return Whether the patient field is set.
       */
      public boolean hasPatient() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       * @return The patient.
       */
      public UserOuterClass.Patient getPatient() {
        if (patientBuilder_ == null) {
          return patient_ == null ? UserOuterClass.Patient.getDefaultInstance() : patient_;
        } else {
          return patientBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder setPatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patient_ = value;
        } else {
          patientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder setPatient(
          UserOuterClass.Patient.Builder builderForValue) {
        if (patientBuilder_ == null) {
          patient_ = builderForValue.build();
        } else {
          patientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder mergePatient(UserOuterClass.Patient value) {
        if (patientBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            patient_ != null &&
            patient_ != UserOuterClass.Patient.getDefaultInstance()) {
            getPatientBuilder().mergeFrom(value);
          } else {
            patient_ = value;
          }
        } else {
          patientBuilder_.mergeFrom(value);
        }
        if (patient_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public Builder clearPatient() {
        bitField0_ = (bitField0_ & ~0x00000020);
        patient_ = null;
        if (patientBuilder_ != null) {
          patientBuilder_.dispose();
          patientBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public UserOuterClass.Patient.Builder getPatientBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getPatientFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      public UserOuterClass.PatientOrBuilder getPatientOrBuilder() {
        if (patientBuilder_ != null) {
          return patientBuilder_.getMessageOrBuilder();
        } else {
          return patient_ == null ?
              UserOuterClass.Patient.getDefaultInstance() : patient_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Patient patient = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>
          getPatientFieldBuilder() {
        if (patientBuilder_ == null) {
          patientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserOuterClass.Patient, UserOuterClass.Patient.Builder, UserOuterClass.PatientOrBuilder>(
                  getPatient(),
                  getParentForChildren(),
                  isClean());
          patient_ = null;
        }
        return patientBuilder_;
      }

      private WardOuterClass.Ward ward_;
      private com.google.protobuf.SingleFieldBuilder<
          WardOuterClass.Ward, WardOuterClass.Ward.Builder, WardOuterClass.WardOrBuilder> wardBuilder_;
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       * @return Whether the ward field is set.
       */
      public boolean hasWard() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       * @return The ward.
       */
      public WardOuterClass.Ward getWard() {
        if (wardBuilder_ == null) {
          return ward_ == null ? WardOuterClass.Ward.getDefaultInstance() : ward_;
        } else {
          return wardBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      public Builder setWard(WardOuterClass.Ward value) {
        if (wardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ward_ = value;
        } else {
          wardBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      public Builder setWard(
          WardOuterClass.Ward.Builder builderForValue) {
        if (wardBuilder_ == null) {
          ward_ = builderForValue.build();
        } else {
          wardBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      public Builder mergeWard(WardOuterClass.Ward value) {
        if (wardBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            ward_ != null &&
            ward_ != WardOuterClass.Ward.getDefaultInstance()) {
            getWardBuilder().mergeFrom(value);
          } else {
            ward_ = value;
          }
        } else {
          wardBuilder_.mergeFrom(value);
        }
        if (ward_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      public Builder clearWard() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ward_ = null;
        if (wardBuilder_ != null) {
          wardBuilder_.dispose();
          wardBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      public WardOuterClass.Ward.Builder getWardBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getWardFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      public WardOuterClass.WardOrBuilder getWardOrBuilder() {
        if (wardBuilder_ != null) {
          return wardBuilder_.getMessageOrBuilder();
        } else {
          return ward_ == null ?
              WardOuterClass.Ward.getDefaultInstance() : ward_;
        }
      }
      /**
       * <code>.com.git_commit_therapy.proto.Ward ward = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          WardOuterClass.Ward, WardOuterClass.Ward.Builder, WardOuterClass.WardOrBuilder>
          getWardFieldBuilder() {
        if (wardBuilder_ == null) {
          wardBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              WardOuterClass.Ward, WardOuterClass.Ward.Builder, WardOuterClass.WardOrBuilder>(
                  getWard(),
                  getParentForChildren(),
                  isClean());
          ward_ = null;
        }
        return wardBuilder_;
      }

      private com.google.protobuf.Internal.IntList medicalExamIds_ = emptyIntList();
      private void ensureMedicalExamIdsIsMutable() {
        if (!medicalExamIds_.isModifiable()) {
          medicalExamIds_ = makeMutableCopy(medicalExamIds_);
        }
        bitField0_ |= 0x00000080;
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @return A list containing the medicalExamIds.
       */
      public java.util.List<java.lang.Integer>
          getMedicalExamIdsList() {
        medicalExamIds_.makeImmutable();
        return medicalExamIds_;
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @return The count of medicalExamIds.
       */
      public int getMedicalExamIdsCount() {
        return medicalExamIds_.size();
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @param index The index of the element to return.
       * @return The medicalExamIds at the given index.
       */
      public int getMedicalExamIds(int index) {
        return medicalExamIds_.getInt(index);
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @param index The index to set the value at.
       * @param value The medicalExamIds to set.
       * @return This builder for chaining.
       */
      public Builder setMedicalExamIds(
          int index, int value) {

        ensureMedicalExamIdsIsMutable();
        medicalExamIds_.setInt(index, value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @param value The medicalExamIds to add.
       * @return This builder for chaining.
       */
      public Builder addMedicalExamIds(int value) {

        ensureMedicalExamIdsIsMutable();
        medicalExamIds_.addInt(value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @param values The medicalExamIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllMedicalExamIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMedicalExamIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, medicalExamIds_);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 medicalExamIds = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMedicalExamIds() {
        medicalExamIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.git_commit_therapy.proto.MedicalEvent)
    }

    // @@protoc_insertion_point(class_scope:com.git_commit_therapy.proto.MedicalEvent)
    private static final MedicalEventOuterClass.MedicalEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MedicalEventOuterClass.MedicalEvent();
    }

    public static MedicalEventOuterClass.MedicalEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MedicalEvent>
        PARSER = new com.google.protobuf.AbstractParser<MedicalEvent>() {
      @java.lang.Override
      public MedicalEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MedicalEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MedicalEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MedicalEventOuterClass.MedicalEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_git_commit_therapy_proto_MedicalEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_git_commit_therapy_proto_MedicalEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023medical_event.proto\022\034com.git_commit_th" +
      "erapy.proto\032\nuser.proto\032\nward.proto\032\037goo" +
      "gle/protobuf/timestamp.proto\"\336\002\n\014Medical" +
      "Event\022\017\n\007eventId\030\001 \001(\005\0220\n\014fromDateTime\030\002" +
      " \001(\0132\032.google.protobuf.Timestamp\022.\n\ntoDa" +
      "teTime\030\003 \001(\0132\032.google.protobuf.Timestamp" +
      "\022@\n\014severityCode\030\004 \001(\0162*.com.git_commit_" +
      "therapy.proto.SeverityCode\022\027\n\017dischargeL" +
      "etter\030\005 \001(\t\0226\n\007patient\030\006 \001(\0132%.com.git_c" +
      "ommit_therapy.proto.Patient\0220\n\004ward\030\007 \001(" +
      "\0132\".com.git_commit_therapy.proto.Ward\022\026\n" +
      "\016medicalExamIds\030\010 \003(\005*E\n\014SeverityCode\022\t\n" +
      "\005WHITE\020\000\022\t\n\005GREEN\020\001\022\n\n\006YELLOW\020\002\022\n\n\006ORANG" +
      "E\020\003\022\007\n\003RED\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          UserOuterClass.getDescriptor(),
          WardOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_git_commit_therapy_proto_MedicalEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_git_commit_therapy_proto_MedicalEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_git_commit_therapy_proto_MedicalEvent_descriptor,
        new java.lang.String[] { "EventId", "FromDateTime", "ToDateTime", "SeverityCode", "DischargeLetter", "Patient", "Ward", "MedicalExamIds", });
    descriptor.resolveAllFeaturesImmutable();
    UserOuterClass.getDescriptor();
    WardOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
